### ISSUE TITLE
Error Issue Last FireFox

### ISSUE THREAD

**Issue by arsium** [LimerBoy/FireFox-Thief#1]
Reading passwords from Firefox browser.
Failed to load NSS

System.ArgumentNullException: value cant' be null.
Parameter : ptr

System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
Decryptor.cs:ligne 62

**Comment by LimerBoy** [comment]
Wich architecture you system have?

**Comment by arsium** [comment]
Last Windows 10 updated and last Firefox

**Comment by LimerBoy** [comment]
64 bit or 32bit?

**Comment by arsium** [comment]
64 bit and I compiled the program both 32 and 64 to avoid this error

**Comment by LimerBoy** [comment]
Try compile program to 64 bit

**Comment by arsium** [comment]
I've already done that and it doesn't work
